import { defineConfig } from '@pandacss/dev';

export default defineConfig({
  preflight: false,
  include: ['./src/**/*.{js,jsx,ts,tsx}', './pages/**/*.{js,jsx,ts,tsx}'],
  exclude: [],
  theme: {
    extend: {
      tokens: {
        colors: {
          brandPrimary: { value: '#47b4eb' },
          brandPrimaryHover: { value: '#3da1d4' },
          brandPrimaryActive: { value: '#338fbc' },
          brandPrimaryStrong: { value: '#256d91' },
          accentSuccess: { value: '#9dbf9e' },
          accentSuccessHover: { value: '#8cae8d' },
          accentSuccessActive: { value: '#7c9d7d' },
          accentSuccessSubtle: { value: '#e8f5e9' },
          accentWarning: { value: '#d4af37' },
          accentWarningHover: { value: '#c2a032' },
          accentWarningActive: { value: '#b0912d' },
          accentWarningSubtle: { value: '#fff9e6' },
          accentError: { value: '#E57373' },
          accentErrorHover: { value: '#E57373' },
          accentErrorActive: { value: '#E57373' },
          accentErrorSubtle: { value: '#ffebee' },
          surfaceBase: { value: '#fdfdfd' },
          surfaceSubtle: { value: '#f8fafc' },
          surfaceMuted: { value: '#e2e8f0' },
          borderSubtle: { value: '#c0cad6' },
          textPrimary: { value: '#2c3e50' },
          effectBrandGlow: { value: 'rgba(71, 180, 235, 0.25)' },
          effectBrandFocus: { value: 'rgba(71, 180, 235, 0.18)' },
        },
        durations: {
          fast: { value: '160ms' },
        },
        fonts: {
          sansDisplay: {
            value: 'Manrope, ui-sans-serif, system-ui, sans-serif',
          },
        },
        fontSizes: {
          uiSm: { value: '0.875rem' },
          uiMd: { value: '0.95rem' },
          uiLg: { value: '1.05rem' },
        },
        fontWeights: {
          button: { value: '700' },
        },
        opacity: {
          disabled: { value: '0.55' },
        },
        radii: {
          sm: { value: '10px' },
          md: { value: '18px' },
          full: { value: '9999px' },
        },
        sizes: {
          controlSm: { value: '2.5rem' },
          controlMd: { value: '3rem' },
          controlLg: { value: '3.5rem' },
        },
        spacing: {
          insetSm: { value: '0.6rem' },
          insetMd: { value: '1rem' },
          insetLg: { value: '1.25rem' },
        },
        shadows: {
          focusRing: { value: '0 0 0 3px rgba(71, 180, 235, 0.18)' },
          focusRingError: { value: '0 0 0 3px rgba(175, 73, 52, 0.12)' },
          focusRingSuccess: { value: '0 0 0 3px rgba(157, 191, 158, 0.12)' },
          focusRingWarning: { value: '0 0 0 3px rgba(224, 174, 66, 0.14)' },
          magicGlow: { value: '0 0 3px rgba(71, 180, 235, 0.25)' },
          softLift: { value: '0 0 3px rgba(44, 62, 80, 0.08)' },
        },
      },
      semanticTokens: {
        colors: {
          inputAdornmentForeground: { value: '{colors.borderSubtle}' },
          inputBackground: { value: '{colors.surfaceBase}' },
          inputBorder: { value: '{colors.borderSubtle}' },
          inputDisabledBackground: { value: '{colors.surfaceSubtle}' },
          inputDisabledBorder: { value: '{colors.borderSubtle}' },
          inputDisabledForeground: { value: '{colors.borderSubtle}' },
          inputErrorBackground: { value: '{colors.accentErrorSubtle}' },
          inputErrorBorder: { value: '{colors.accentError}' },
          inputErrorForeground: { value: '{colors.accentError}' },
          inputFocusBorder: { value: '{colors.brandPrimary}' },
          inputForeground: { value: '{colors.textPrimary}' },
          inputHelperForeground: { value: '{colors.textPrimary}' },
          inputMessageForeground: { value: '{colors.brandPrimary}' },
          inputPlaceholder: { value: '{colors.borderSubtle}' },
          inputSuccessBackground: { value: '{colors.accentSuccessSubtle}' },
          inputSuccessBorder: { value: '{colors.accentSuccess}' },
          inputSuccessForeground: { value: '{colors.accentSuccess}' },
          inputWarningBackground: { value: '{colors.accentWarningSubtle}' },
          inputWarningBorder: { value: '{colors.accentWarning}' },
          inputWarningForeground: { value: '{colors.accentWarning}' },
          actionGhostPrimaryBackgroundHover: {
            value: '{colors.surfaceSubtle}',
          },
          actionGhostPrimaryBorder: { value: 'transparent' },
          actionGhostPrimaryForeground: { value: '{colors.brandPrimary}' },
          actionGhostSuccessBackgroundHover: {
            value: '{colors.accentSuccessSubtle}',
          },
          actionGhostSuccessBorder: { value: 'transparent' },
          actionGhostSuccessForeground: { value: '{colors.accentSuccess}' },
          actionGhostWarningBackgroundHover: {
            value: '{colors.accentWarningSubtle}',
          },
          actionGhostWarningBorder: { value: 'transparent' },
          actionGhostWarningForeground: { value: '{colors.accentWarning}' },
          actionGhostErrorBackgroundHover: {
            value: '{colors.accentErrorSubtle}',
          },
          actionGhostErrorBorder: { value: 'transparent' },
          actionGhostErrorForeground: { value: '{colors.accentError}' },
          actionOutlinePrimaryBackground: { value: '{colors.surfaceBase}' },
          actionOutlinePrimaryBackgroundHover: {
            value: '{colors.surfaceSubtle}',
          },
          actionOutlinePrimaryBorder: { value: '{colors.borderSubtle}' },
          actionOutlinePrimaryBorderHover: { value: '{colors.brandPrimary}' },
          actionOutlinePrimaryForeground: { value: '{colors.brandPrimary}' },
          actionOutlineSuccessBackground: { value: '{colors.surfaceBase}' },
          actionOutlineSuccessBackgroundHover: {
            value: '{colors.accentSuccessSubtle}',
          },
          actionOutlineSuccessBorder: { value: '{colors.accentSuccess}' },
          actionOutlineSuccessBorderHover: {
            value: '{colors.accentSuccessHover}',
          },
          actionOutlineSuccessForeground: { value: '{colors.accentSuccess}' },
          actionOutlineWarningBackground: { value: '{colors.surfaceBase}' },
          actionOutlineWarningBackgroundHover: {
            value: '{colors.accentWarningSubtle}',
          },
          actionOutlineWarningBorder: { value: '{colors.accentWarning}' },
          actionOutlineWarningBorderHover: {
            value: '{colors.accentWarningHover}',
          },
          actionOutlineWarningForeground: { value: '{colors.accentWarning}' },
          actionOutlineErrorBackground: { value: '{colors.surfaceBase}' },
          actionOutlineErrorBackgroundHover: {
            value: '{colors.accentErrorSubtle}',
          },
          actionOutlineErrorBorder: { value: '{colors.accentError}' },
          actionOutlineErrorBorderHover: { value: '{colors.accentErrorHover}' },
          actionOutlineErrorForeground: { value: '{colors.accentError}' },
          actionIconPrimaryBackground: { value: '{colors.surfaceBase}' },
          actionIconPrimaryBackgroundHover: { value: '{colors.surfaceSubtle}' },
          actionIconPrimaryBorder: { value: '{colors.borderSubtle}' },
          actionIconPrimaryBorderHover: { value: '{colors.brandPrimary}' },
          actionIconPrimaryForeground: { value: '{colors.brandPrimary}' },
          actionIconSuccessBackground: { value: '{colors.surfaceBase}' },
          actionIconSuccessBackgroundHover: {
            value: '{colors.accentSuccessSubtle}',
          },
          actionIconSuccessBorder: { value: '{colors.accentSuccess}' },
          actionIconSuccessBorderHover: {
            value: '{colors.accentSuccessHover}',
          },
          actionIconSuccessForeground: { value: '{colors.accentSuccess}' },
          actionIconWarningBackground: { value: '{colors.surfaceBase}' },
          actionIconWarningBackgroundHover: {
            value: '{colors.accentWarningSubtle}',
          },
          actionIconWarningBorder: { value: '{colors.accentWarning}' },
          actionIconWarningBorderHover: {
            value: '{colors.accentWarningHover}',
          },
          actionIconWarningForeground: { value: '{colors.accentWarning}' },
          actionIconErrorBackground: { value: '{colors.surfaceBase}' },
          actionIconErrorBackgroundHover: {
            value: '{colors.accentErrorSubtle}',
          },
          actionIconErrorBorder: { value: '{colors.accentError}' },
          actionIconErrorBorderHover: { value: '{colors.accentErrorHover}' },
          actionIconErrorForeground: { value: '{colors.accentError}' },
          actionSolidPrimaryBackground: { value: '{colors.brandPrimary}' },
          actionSolidPrimaryBackgroundHover: {
            value: '{colors.brandPrimaryHover}',
          },
          actionSolidPrimaryBackgroundActive: {
            value: '{colors.brandPrimaryActive}',
          },
          actionSolidPrimaryBorder: { value: '{colors.brandPrimary}' },
          actionSolidPrimaryBorderHover: {
            value: '{colors.brandPrimaryHover}',
          },
          actionSolidPrimaryForeground: { value: '{colors.surfaceBase}' },
          actionSolidSuccessBackground: { value: '{colors.accentSuccess}' },
          actionSolidSuccessBackgroundHover: {
            value: '{colors.accentSuccessHover}',
          },
          actionSolidSuccessBackgroundActive: {
            value: '{colors.accentSuccessActive}',
          },
          actionSolidSuccessBorder: { value: '{colors.accentSuccess}' },
          actionSolidSuccessBorderHover: {
            value: '{colors.accentSuccessHover}',
          },
          actionSolidSuccessForeground: { value: '{colors.textPrimary}' },
          actionSolidWarningBackground: { value: '{colors.accentWarning}' },
          actionSolidWarningBackgroundHover: {
            value: '{colors.accentWarningHover}',
          },
          actionSolidWarningBackgroundActive: {
            value: '{colors.accentWarningActive}',
          },
          actionSolidWarningBorder: { value: '{colors.accentWarning}' },
          actionSolidWarningBorderHover: {
            value: '{colors.accentWarningHover}',
          },
          actionSolidWarningForeground: { value: '{colors.textPrimary}' },
          actionSolidErrorBackground: { value: '{colors.accentError}' },
          actionSolidErrorBackgroundHover: {
            value: '{colors.accentErrorHover}',
          },
          actionSolidErrorBackgroundActive: {
            value: '{colors.accentErrorActive}',
          },
          actionSolidErrorBorder: { value: '{colors.accentError}' },
          actionSolidErrorBorderHover: { value: '{colors.accentErrorHover}' },
          actionSolidErrorForeground: { value: '{colors.surfaceBase}' },
          cardAccentForeground: { value: '{colors.surfaceBase}' },
          cardBackground: { value: '{colors.surfaceBase}' },
          cardBorder: { value: '{colors.borderSubtle}' },
          cardBorderHover: { value: '{colors.brandPrimary}' },
          cardForeground: { value: '{colors.textPrimary}' },
          cardMutedForeground: { value: '{colors.borderSubtle}' },
          cardSubtleBorder: { value: '{colors.borderSubtle}' },
          focusRingColor: { value: '{colors.effectBrandFocus}' },
          borderAccentSubtle: { value: 'rgba(255, 255, 255, 0.14)' },
          borderAccentStrong: { value: '{colors.brandPrimaryStrong}' },
          borderInteractiveMuted: { value: '{colors.borderSubtle}' },
          borderNeutralMuted: { value: 'rgba(192, 202, 214, 0.32)' },
          borderStatusInfoSubtle: { value: 'rgba(71, 180, 235, 0.18)' },
          borderStatusSuccessSubtle: { value: 'rgba(157, 191, 158, 0.22)' },
          borderStatusWarningSubtle: { value: 'rgba(212, 175, 55, 0.22)' },
          foregroundMuted: { value: 'rgba(44, 62, 80, 0.82)' },
          foregroundMutedSubtle: { value: 'rgba(44, 62, 80, 0.7)' },
          foregroundOnAccentMuted: { value: 'rgba(253, 253, 253, 0.82)' },
          surfaceInteractiveMuted: { value: '{colors.surfaceMuted}' },
          surfaceStatusInfoSubtle: { value: 'rgba(71, 180, 235, 0.12)' },
          surfaceAccentStrong: { value: '{colors.brandPrimaryStrong}' },
          surfaceTintedAccentHover: { value: 'rgba(71, 180, 235, 0.08)' },
        },
      },
    },
  },
  outdir: 'styled-system',
});
