import type { CSSProperties, PropsWithChildren } from 'react';

/**
 * Built-in color theme names shipped by the library.
 */
export type UiBuiltinThemeName = 'dark' | 'light';

/**
 * Special theme mode that follows the user's operating system preference.
 */
export type UiSystemThemeName = 'system';

/**
 * Theme value accepted by the provider.
 *
 * Custom theme names can be registered through the `themes` prop.
 */
export type UiThemeName = string | UiSystemThemeName;

/**
 * Overrideable color token names exposed by the theme provider.
 *
 * These tokens map to the CSS variables generated by Panda and can be used to
 * create custom branded themes without editing component code.
 */
export type UiThemeColorTokens = Partial<{
  accentError: string;
  accentErrorActive: string;
  accentErrorHover: string;
  accentErrorSubtle: string;
  accentSuccess: string;
  accentSuccessActive: string;
  accentSuccessHover: string;
  accentSuccessSubtle: string;
  accentWarning: string;
  accentWarningActive: string;
  accentWarningHover: string;
  accentWarningSubtle: string;
  borderAccentStrong: string;
  borderAccentSubtle: string;
  borderInteractiveMuted: string;
  borderNeutralMuted: string;
  borderStatusInfoSubtle: string;
  borderStatusSuccessSubtle: string;
  borderStatusWarningSubtle: string;
  borderSubtle: string;
  brandPrimary: string;
  brandPrimaryActive: string;
  brandPrimaryHover: string;
  brandPrimaryStrong: string;
  cardAccentForeground: string;
  cardBackground: string;
  cardBorder: string;
  cardBorderHover: string;
  cardForeground: string;
  cardMutedForeground: string;
  cardSubtleBorder: string;
  effectBrandFocus: string;
  effectBrandGlow: string;
  focusRingColor: string;
  foregroundMuted: string;
  foregroundMutedSubtle: string;
  foregroundOnAccentMuted: string;
  inputAdornmentForeground: string;
  inputBackground: string;
  inputBorder: string;
  inputDisabledBackground: string;
  inputDisabledBorder: string;
  inputDisabledForeground: string;
  inputErrorBackground: string;
  inputErrorBorder: string;
  inputErrorForeground: string;
  inputFocusBorder: string;
  inputForeground: string;
  inputHelperForeground: string;
  inputMessageForeground: string;
  inputPlaceholder: string;
  inputSuccessBackground: string;
  inputSuccessBorder: string;
  inputSuccessForeground: string;
  inputWarningBackground: string;
  inputWarningBorder: string;
  inputWarningForeground: string;
  surfaceAccentStrong: string;
  surfaceBase: string;
  surfaceInteractiveMuted: string;
  surfaceMuted: string;
  surfaceStatusInfoSubtle: string;
  surfaceSubtle: string;
  surfaceTintedAccentHover: string;
  textPrimary: string;
}>;

/**
 * Shape of a named custom theme registered in the provider.
 */
export type UiThemeDefinition = {
  colors?: UiThemeColorTokens;
};

/**
 * Collection of named themes available to the provider.
 */
export type UiThemeRegistry = Record<string, UiThemeDefinition>;

/**
 * Props accepted by the library theme provider.
 */
export type UiThemeProviderProps = PropsWithChildren<
  Partial<{
    /**
     * Adds custom inline styles to the wrapper element.
     */
    style: CSSProperties;
    /**
     * Adds a custom class name to the wrapper element.
     */
    className: string;
    /**
     * Selects the active theme name or follows the system preference.
     * @default 'light'
     */
    theme: UiThemeName;
    /**
     * Registers additional named themes that can be selected through `theme`.
     */
    themes: UiThemeRegistry;
    /**
     * Applies token overrides on top of the resolved theme.
     */
    tokens: UiThemeColorTokens;
  }>
>;

/**
 * Context value exposed by the library theme provider.
 */
export type UiThemeContextValue = {
  resolvedTheme: UiBuiltinThemeName | string;
  theme: UiThemeName;
  tokens: UiThemeColorTokens;
};
